version: '3'

tasks:

  go-sqlc-generate:
    cmds:
      - go tool sqlc generate
    dir: pkg/apps/main/persistence/storage/gensql/gen_sql_src
    generates:
      - pkg/apps/main/persistence/storage/gensql/gen_sql_dst/*.go

  db-up:
    cmds:
      - docker compose up --force-recreate --no-deps db db-setup

  db-down:
    cmds:
      - docker compose stop --timeout 0 db db-setup
      - docker compose rm --volumes --force db db-setup

  db-inspect:
    cmds:
      - docker compose run --rm --no-deps db-shell

  api-backend-run:
    cmds:
      - docker compose up --build --force-recreate --no-deps --menu api-backend

  api-client-run:
    cmds:
      - docker compose run --build --rm --no-deps api-client
